### ISSUE TITLE
Add short description of what this library does in the README

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/dashboard-js#3]
As a new User I want to know what this is and what it does so that I can decide whether to investigate further
 
This is a library and pattern for quickly creating dashboards using data package data sources. It is lightweight and easy to customize.
 
Requires only knowledge of HTML and CSS
Extendable: base widgets are simple react and you can build your own or extend

## Acceptance criteria

* [x] I have a section about what this library does in the README
* [x] There is no syntax errors (you need to proof read)

## Tasks

* [x] create a draft of the section you going to add
* [x] get it reviewed by somebody
* [x] improve per feedback
* [x] push to github

**Comment by anuveyatsu** [comment]
FIXED see the updated README's beginning
