### ISSUE TITLE
Figure widget improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/dashboard-js#5]
## Acceptance criteria

* [x] Figure widget supports transforms

## Tasks

* [x] move spec up to view object so that only `suffix` and `prefix` will remain
* [x] re-use transforms from datapackage-render-js
* [x] change suffix to a simple text “prefix{value}suffix”
  * If not defined just render the number otherwise render that text
* [x] remove logic showing last/first data - it should expect just 1 row and should render specific elements from that row

## Analysis

Figure spec should be minimal, e.g., title, legend etc should go up into "view" object. The following properties will be kept in Figure spec:

* `suffix` and `prefix` - these are optional, see example below
* `fieldName` - a name of the target field. It is needed since after transformation we will have a single row as a dictionary of `field: value` pair

**Comment by anuveyatsu** [comment]
FIXED and rebuilt. See how we now write a Figure spec:

https://github.com/datahq/city-indicators/blob/master/widgets/economy.json#L4-L26

Note that:

* metadata have been moved to "view" object
* transform object to identify the most recent data
